version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: narxozer
      POSTGRES_USER: olzzhas
      POSTGRES_PASSWORD: Olzhas040404
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U olzzhas"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_DSN: "postgres://olzzhas:Olzhas040404@db:5432/narxozer?sslmode=disable"
      PORT: 4000
    ports:
      - "4000:4000"
    command: ["sh", "-c", "sleep 10 && /narxozer"]

volumes:
  postgres_data:  # Определение тома
