services:
  - name: narxozer-db
    type: database
    database_name: narxozer
    user: olzzhas
    password: Olzhas040404
    starter_plan: micro
    database_type: postgres

  - name: narxozer-redis
    type: redis
    starter_plan: free

  - name: narxozer-migrate
    type: web
    env: docker
    dockerfilePath: Dockerfile
    entrypoint: ["sh", "-c", "sleep 10 && migrate -path /migrations -database postgres://olzzhas:Olzhas040404@db:5432/narxozer?sslmode=disable up"]
    depends_on:
      - name: narxozer-db
      - name: narxozer-redis
    buildCommand: ""
    startCommand: ""

  - name: narxozer-app
    type: web
    env: docker
    dockerfilePath: Dockerfile
    ports:
      - 4000
    depends_on:
      - name: narxozer-db
      - name: narxozer-redis
      - name: narxozer-migrate
    buildCommand: ""
    startCommand: ["/narxozer"]
    envVars:
      - key: DB_DSN
        value: postgres://olzzhas:Olzhas040404@narxozer-db:5432/narxozer?sslmode=disable
      - key: REDIS_URL
        value: redis://narxozer-redis:6379
