// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type AuthPayload struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type Club struct {
	ID          int      `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	ImageURL    *string  `json:"imageURL,omitempty"`
	Creator     *User    `json:"creator"`
	CreatedAt   string   `json:"createdAt"`
	Members     []*User  `json:"members"`
	Events      []*Event `json:"events"`
	Admins      []*User  `json:"admins"`
}

type Comment struct {
	ID         int        `json:"id"`
	Content    string     `json:"content"`
	EntityID   int        `json:"entityId"`
	EntityType string     `json:"entityType"`
	AuthorID   int        `json:"authorId"`
	ParentID   *int       `json:"parentId,omitempty"`
	CreatedAt  string     `json:"createdAt"`
	UpdatedAt  *string    `json:"updatedAt,omitempty"`
	Likes      int        `json:"likes"`
	Replies    []*Comment `json:"replies"`
}

type CreateClubInput struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	ImageURL    *string `json:"imageURL,omitempty"`
}

type CreateCommentInput struct {
	EntityID   int    `json:"entityID"`
	EntityType string `json:"entityType"`
	Content    string `json:"content"`
	AuthorID   int    `json:"authorId"`
	ParentID   *int   `json:"parentId,omitempty"`
}

type CreateEventInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Date        string `json:"date"`
}

type CreatePostInput struct {
	Title    string  `json:"title"`
	Content  string  `json:"content"`
	ImageURL *string `json:"imageURL,omitempty"`
	AuthorID int     `json:"authorId"`
}

type CreateTopicInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type CreateUserInput struct {
	Email                 string  `json:"email"`
	Name                  string  `json:"name"`
	Lastname              string  `json:"lastname"`
	Password              string  `json:"password"`
	Role                  Role    `json:"role"`
	ImageURL              *string `json:"imageURL,omitempty"`
	AdditionalInformation *string `json:"additionalInformation,omitempty"`
	Course                *int    `json:"course,omitempty"`
	Major                 *string `json:"major,omitempty"`
	Degree                *string `json:"degree,omitempty"`
	Faculty               *string `json:"faculty,omitempty"`
}

type Event struct {
	ID          int    `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	CreatedAt   string `json:"createdAt"`
	Date        string `json:"date"`
	ClubID      int    `json:"clubId"`
}

type Mutation struct {
}

type Post struct {
	ID        int        `json:"id"`
	Title     string     `json:"title"`
	Content   string     `json:"content"`
	ImageURL  *string    `json:"imageURL,omitempty"`
	AuthorID  int        `json:"authorId"`
	CreatedAt string     `json:"createdAt"`
	UpdatedAt *string    `json:"updatedAt,omitempty"`
	Likes     int        `json:"likes"`
	Comments  []*Comment `json:"comments"`
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Lastname string `json:"lastname"`
	Password string `json:"password"`
}

type Topic struct {
	ID        int        `json:"id"`
	Title     string     `json:"title"`
	Content   string     `json:"content"`
	AuthorID  int        `json:"authorId"`
	CreatedAt string     `json:"createdAt"`
	UpdatedAt *string    `json:"updatedAt,omitempty"`
	Likes     int        `json:"likes"`
	Comments  []*Comment `json:"comments"`
}

type UpdateClubInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	ImageURL    *string `json:"imageURL,omitempty"`
}

type UpdateCommentInput struct {
	Content  string `json:"content"`
	AuthorID int    `json:"authorId"`
	ParentID *int   `json:"parentId,omitempty"`
}

type UpdateEventInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Date        *string `json:"date,omitempty"`
}

type UpdatePostInput struct {
	Title    *string `json:"title,omitempty"`
	Content  *string `json:"content,omitempty"`
	ImageURL *string `json:"imageURL,omitempty"`
}

type UpdateTopicInput struct {
	Title   *string `json:"title,omitempty"`
	Content *string `json:"content,omitempty"`
}

type UpdateUserInput struct {
	Email                 *string `json:"email,omitempty"`
	Name                  *string `json:"name,omitempty"`
	Lastname              *string `json:"lastname,omitempty"`
	Password              *string `json:"password,omitempty"`
	Role                  *Role   `json:"role,omitempty"`
	ImageURL              *string `json:"imageURL,omitempty"`
	AdditionalInformation *string `json:"additionalInformation,omitempty"`
	Course                *int    `json:"course,omitempty"`
	Major                 *string `json:"major,omitempty"`
	Degree                *string `json:"degree,omitempty"`
	Faculty               *string `json:"faculty,omitempty"`
}

type User struct {
	ID                    int     `json:"id"`
	Email                 string  `json:"email"`
	Name                  string  `json:"name"`
	Lastname              string  `json:"lastname"`
	PasswordHash          string  `json:"passwordHash"`
	Role                  Role    `json:"role"`
	ImageURL              *string `json:"imageURL,omitempty"`
	AdditionalInformation *string `json:"additionalInformation,omitempty"`
	Course                *int    `json:"course,omitempty"`
	CreatedAt             string  `json:"createdAt"`
	UpdatedAt             *string `json:"updatedAt,omitempty"`
	Major                 *string `json:"major,omitempty"`
	Degree                *string `json:"degree,omitempty"`
	Faculty               *string `json:"faculty,omitempty"`
}

type Role string

const (
	RoleStudent Role = "STUDENT"
	RoleTeacher Role = "TEACHER"
	RoleAdmin   Role = "ADMIN"
)

var AllRole = []Role{
	RoleStudent,
	RoleTeacher,
	RoleAdmin,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleStudent, RoleTeacher, RoleAdmin:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
